import type { Phoneme, PronunciationNote } from '../types'

/**
 * The 44 sounds of English as learner dictionaries transcribe them: 12 monophthongs,
 * 8 diphthongs, 24 consonants. Symbols follow the British set our own entries carry in
 * `lex.pronunciations.ipa`, with `gaSymbol` filled only where General American differs.
 *
 * The two weak vowels /i/ and /u/ follow them. They are not a 45th and 46th phoneme:
 * each stands for a sound that moves between a long and a short vowel when unstressed,
 * and dictionaries print them in happy and in usually. They are here because our own
 * transcriptions carry them, and a symbol with no card is a symbol with no link.
 */
export const PHONEMES: readonly Phoneme[] = [
  {
    symbol: 'ɪ',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'KIT',
    howVi: 'Lưỡi cao vừa phải, miệng thả lỏng, âm bật ra rồi tắt ngay.',
    trapVi: 'Hệ nguyên âm tiếng Việt không có ô nào nằm giữa "i" và "ê", nên /ɪ/ bị dồn vào "i" và kéo dài theo. Lưỡi phải hạ xuống một chút và âm phải dứt ngay.',
    spellings: ['i', 'y', 'ui', 'e'],
    examples: [
      { word: 'ship', ipa: '/ʃɪp/', spelling: 'i' },
      { word: 'gym', ipa: '/dʒɪm/', spelling: 'y' },
      { word: 'build', ipa: '/bɪld/', spelling: 'ui' },
    ],
    minimalPair: { a: 'ship', ipaA: '/ʃɪp/', b: 'sheep', ipaB: '/ʃiːp/' },
  },
  {
    symbol: 'e',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'DRESS',
    howVi: 'Lưỡi ở giữa và hơi ra trước, miệng mở vừa. Gần với "e" trong "em".',
    trapVi: 'Ô "e" trong "em" trùng với /e/ nên chặng này không khó; cái khó là giữ nó tách khỏi /æ/. Miệng mở chưa đủ rộng thì bad nghe thành bed.',
    spellings: ['e', 'ea', 'a', 'ai', 'ie', 'eo'],
    examples: [
      { word: 'bed', ipa: '/bed/', spelling: 'e' },
      { word: 'head', ipa: '/hed/', spelling: 'ea' },
      { word: 'friend', ipa: '/frend/', spelling: 'ie' },
    ],
    minimalPair: { a: 'bed', ipaA: '/bed/', b: 'bad', ipaB: '/bæd/' },
  },
  {
    symbol: 'æ',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'TRAP',
    howVi: 'Hạ hàm xuống thấp, lưỡi thấp và ra trước, miệng mở rộng theo chiều ngang.',
    trapVi: 'Khoảng giữa "a" và "e" tiếng Việt bỏ trống, nên người học chọn một trong hai và man thành men. Hàm phải hạ thấp hơn cả khi đọc "a".',
    spellings: ['a', 'ai'],
    examples: [
      { word: 'cat', ipa: '/kæt/', spelling: 'a' },
      { word: 'hand', ipa: '/hænd/', spelling: 'a' },
      { word: 'apple', ipa: '/ˈæpl/', spelling: 'a' },
    ],
    minimalPair: { a: 'man', ipaA: '/mæn/', b: 'men', ipaB: '/men/' },
  },
  {
    symbol: 'ɒ',
    gaSymbol: 'ɑ',
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'LOT',
    howVi: 'Lưỡi lùi về sau và hạ thấp, môi tròn nhẹ, âm ngắn.',
    trapVi: 'Chữ o tiếng Việt luôn đọc dài, nên /ɒ/ bị kéo ra và shot lẫn với short. Cặp này phân biệt bằng độ dài, /ɒ/ ngắn còn /ɔː/ dài.',
    spellings: ['o', 'a sau w', 'au', 'ou'],
    examples: [
      { word: 'hot', ipa: '/hɒt/', spelling: 'o' },
      { word: 'watch', ipa: '/wɒtʃ/', spelling: 'a sau w' },
      { word: 'because', ipa: '/bɪˈkɒz/', spelling: 'au' },
    ],
    minimalPair: { a: 'shot', ipaA: '/ʃɒt/', b: 'short', ipaB: '/ʃɔːt/' },
  },
  {
    symbol: 'ʌ',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'STRUT',
    howVi: 'Lưỡi ở giữa và hơi thấp, môi không tròn, cơ miệng thả lỏng. Gần với "ă" hơn là "u".',
    trapVi: 'Mặt chữ u dẫn về "u" tiếng Việt với môi chúm tròn, nên but nghe thành "bút". Môi phải dẹt và lưỡi nằm giữa khoang miệng.',
    spellings: ['u', 'o', 'ou', 'oo'],
    examples: [
      { word: 'cup', ipa: '/kʌp/', spelling: 'u' },
      { word: 'love', ipa: '/lʌv/', spelling: 'o' },
      { word: 'young', ipa: '/jʌŋ/', spelling: 'ou' },
    ],
    minimalPair: { a: 'cup', ipaA: '/kʌp/', b: 'cap', ipaB: '/kæp/' },
  },
  {
    symbol: 'ʊ',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'FOOT',
    howVi: 'Lưỡi lùi về sau và lên cao vừa phải, môi tròn nhẹ. Âm ngắn và lỏng.',
    trapVi: 'Âm "u" tiếng Việt căng và dài hơn /ʊ/, thay vào đây thì full không còn khác fool. Môi chỉ tròn hờ, cơ lưỡi buông lỏng.',
    spellings: ['oo', 'u', 'o', 'ou'],
    examples: [
      { word: 'book', ipa: '/bʊk/', spelling: 'oo' },
      { word: 'put', ipa: '/pʊt/', spelling: 'u' },
      { word: 'could', ipa: '/kʊd/', spelling: 'ou' },
    ],
    minimalPair: { a: 'full', ipaA: '/fʊl/', b: 'fool', ipaB: '/fuːl/' },
  },
  {
    symbol: 'ə',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm ngắn',
    keyword: 'commA',
    howVi: 'Lưỡi nằm giữa khoang miệng, môi không làm gì cả. Đây là âm của miệng khi buông lỏng hoàn toàn.',
    trapVi: 'Mỗi âm tiết tiếng Việt mang một thanh điệu và được đọc rõ như nhau, nên người học phát âm đủ nguyên âm ở chỗ đáng lẽ phải nhẹ đi. Bất kỳ chữ cái nguyên âm nào cũng có thể rút về /ə/.',
    spellings: ['a', 'e', 'o', 'u', 'er', 'ou'],
    examples: [
      { word: 'about', ipa: '/əˈbaʊt/', spelling: 'a' },
      { word: 'teacher', ipa: '/ˈtiːtʃə/', spelling: 'er' },
      { word: 'problem', ipa: '/ˈprɒbləm/', spelling: 'e' },
    ],
    minimalPair: null,
  },
  {
    symbol: 'iː',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm dài',
    keyword: 'FLEECE',
    howVi: 'Lưỡi đưa cao và ra trước, môi dẹt như đang cười, giữ âm dài.',
    trapVi: 'Gần như trùng với "i" tiếng Việt, chỉ khác ở độ dài, nên lỗi duy nhất là đọc cụt và sheep hoá ship.',
    spellings: ['ee', 'ea', 'e_e', 'ie', 'i', 'ey'],
    examples: [
      { word: 'sheep', ipa: '/ʃiːp/', spelling: 'ee' },
      { word: 'eat', ipa: '/iːt/', spelling: 'ea' },
      { word: 'machine', ipa: '/məˈʃiːn/', spelling: 'i' },
    ],
    minimalPair: { a: 'sheep', ipaA: '/ʃiːp/', b: 'ship', ipaB: '/ʃɪp/' },
  },
  {
    symbol: 'ɑː',
    gaSymbol: 'ɑːr',
    kind: 'vowel',
    groupVi: 'Nguyên âm dài',
    keyword: 'PALM',
    howVi: 'Hạ hàm, lưỡi thấp và lùi về sau, môi không tròn. Giữ âm dài.',
    trapVi: 'Ngay cả "a" dài nhất của tiếng Việt cũng ngắn hơn /ɑː/, nên cart bị rút về cut. Phiên âm Anh-Anh không đọc chữ r theo sau, car là /kɑː/.',
    spellings: ['ar', 'a', 'al', 'au', 'ear'],
    examples: [
      { word: 'car', ipa: '/kɑː/', spelling: 'ar' },
      { word: 'father', ipa: '/ˈfɑːðə/', spelling: 'a' },
      { word: 'heart', ipa: '/hɑːt/', spelling: 'ear' },
    ],
    minimalPair: { a: 'cart', ipaA: '/kɑːt/', b: 'cut', ipaB: '/kʌt/' },
  },
  {
    symbol: 'ɔː',
    gaSymbol: 'ɔːr',
    kind: 'vowel',
    groupVi: 'Nguyên âm dài',
    keyword: 'THOUGHT',
    howVi: 'Lưỡi lùi về sau, môi tròn và đẩy ra trước, giữ âm dài.',
    trapVi: 'Môi chưa tròn đủ và âm chưa đủ dài thì short trùng với shot. Đây là cặp dài và ngắn, không phải hai chất giọng khác nhau.',
    spellings: ['or', 'oor', 'au', 'aw', 'al', 'ough', 'oar'],
    examples: [
      { word: 'door', ipa: '/dɔː/', spelling: 'oor' },
      { word: 'call', ipa: '/kɔːl/', spelling: 'al' },
      { word: 'law', ipa: '/lɔː/', spelling: 'aw' },
    ],
    minimalPair: { a: 'short', ipaA: '/ʃɔːt/', b: 'shot', ipaB: '/ʃɒt/' },
  },
  {
    symbol: 'uː',
    gaSymbol: null,
    kind: 'vowel',
    groupVi: 'Nguyên âm dài',
    keyword: 'GOOSE',
    howVi: 'Lưỡi cao và lùi về sau, môi chúm tròn, giữ âm dài.',
    trapVi: 'Vì "u" tiếng Việt ngắn hơn, fool rơi xuống thành full. Sau một số phụ âm còn có thêm /j/ đứng trước, music là /ˈmjuːzɪk/.',
    spellings: ['oo', 'u_e', 'ue', 'ew', 'o', 'ou'],
    examples: [
      { word: 'food', ipa: '/fuːd/', spelling: 'oo' },
      { word: 'blue', ipa: '/bluː/', spelling: 'ue' },
      { word: 'do', ipa: '/duː/', spelling: 'o' },
    ],
    minimalPair: { a: 'fool', ipaA: '/fuːl/', b: 'full', ipaB: '/fʊl/' },
  },
  {
    symbol: 'ɜː',
    gaSymbol: 'ɜr',
    kind: 'vowel',
    groupVi: 'Nguyên âm dài',
    keyword: 'NURSE',
    howVi: 'Lưỡi nằm giữa khoang miệng, môi dẹt, giữ nguyên một chỗ và kéo dài. Là âm /ə/ kéo dài ra.',
    trapVi: 'Tiếng Việt đọc mọi chữ cái phụ âm có mặt, nên chữ r trong bird bị phát ra thành một âm riêng. Giọng Anh-Anh chỉ có một nguyên âm dài ở đây.',
    spellings: ['ir', 'ur', 'er', 'ear', 'or sau w', 'our'],
    examples: [
      { word: 'bird', ipa: '/bɜːd/', spelling: 'ir' },
      { word: 'work', ipa: '/wɜːk/', spelling: 'or sau w' },
      { word: 'learn', ipa: '/lɜːn/', spelling: 'ear' },
    ],
    minimalPair: { a: 'work', ipaA: '/wɜːk/', b: 'walk', ipaB: '/wɔːk/' },
  },
  {
    symbol: 'i',
    gaSymbol: null,
    kind: 'weak',
    groupVi: 'Nguyên âm yếu',
    keyword: 'happY',
    howVi: 'Đứng ở âm tiết không mang trọng âm, cuối từ hoặc trước một nguyên âm. Đọc như /iː/ nhưng ngắn, và không được nhấn.',
    trapVi: 'Do mọi âm tiết tiếng Việt đều mang trọng lượng ngang nhau, city bị đọc thành hai tiếng đều. Âm tiết đầu nhận trọng âm, phần còn lại nhẹ đi.',
    spellings: ['y cuối từ', 'i', 'ey', 'ie'],
    examples: [
      { word: 'happy', ipa: '/ˈhæpi/', spelling: 'y cuối từ' },
      { word: 'city', ipa: '/ˈsɪti/', spelling: 'y cuối từ' },
      { word: 'money', ipa: '/ˈmʌni/', spelling: 'ey' },
    ],
    minimalPair: null,
  },
  {
    symbol: 'u',
    gaSymbol: null,
    kind: 'weak',
    groupVi: 'Nguyên âm yếu',
    keyword: 'sitUation',
    howVi: 'Đứng trước một nguyên âm khác ở âm tiết không mang trọng âm. Đọc như /uː/ nhưng ngắn và nhẹ.',
    trapVi: 'Người học kéo âm này thành /uː/ rồi nhấn vào nó, nên usually rời ra thành bốn tiếng rõ. Nó chỉ là một chặng lướt giữa hai nguyên âm.',
    spellings: ['u trước nguyên âm'],
    examples: [
      { word: 'usually', ipa: '/ˈjuːʒuəli/', spelling: 'u trước nguyên âm' },
      { word: 'influence', ipa: '/ˈɪnfluəns/', spelling: 'u trước nguyên âm' },
      { word: 'actual', ipa: '/ˈæktʃuəl/', spelling: 'u trước nguyên âm' },
    ],
    minimalPair: null,
  },
  {
    symbol: 'eɪ',
    gaSymbol: null,
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi khép',
    keyword: 'FACE',
    howVi: 'Bắt đầu ở /e/ rồi trượt lên /ɪ/. Miệng khép dần trong một hơi.',
    trapVi: 'Nguyên âm đôi "ây" có sẵn chặng trượt tương tự, nhưng mặt chữ a kéo người học về "ê" đơn và late thành "lết".',
    spellings: ['a_e', 'ai', 'ay', 'ei', 'ey', 'ea'],
    examples: [
      { word: 'name', ipa: '/neɪm/', spelling: 'a_e' },
      { word: 'day', ipa: '/deɪ/', spelling: 'ay' },
      { word: 'wait', ipa: '/weɪt/', spelling: 'ai' },
    ],
    minimalPair: { a: 'late', ipaA: '/leɪt/', b: 'let', ipaB: '/let/' },
  },
  {
    symbol: 'aɪ',
    gaSymbol: null,
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi khép',
    keyword: 'PRICE',
    howVi: 'Bắt đầu ở nguyên âm mở phía trước rồi trượt lên /ɪ/. Gần với "ai" trong "hai".',
    trapVi: null,
    spellings: ['i_e', 'y', 'igh', 'ie', 'ei', 'uy'],
    examples: [
      { word: 'time', ipa: '/taɪm/', spelling: 'i_e' },
      { word: 'my', ipa: '/maɪ/', spelling: 'y' },
      { word: 'night', ipa: '/naɪt/', spelling: 'igh' },
    ],
    minimalPair: { a: 'time', ipaA: '/taɪm/', b: 'tame', ipaB: '/teɪm/' },
  },
  {
    symbol: 'ɔɪ',
    gaSymbol: null,
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi khép',
    keyword: 'CHOICE',
    howVi: 'Bắt đầu ở /ɔː/ với môi tròn rồi trượt lên /ɪ/, môi dẹt dần. Gần với "oi" trong "coi".',
    trapVi: null,
    spellings: ['oi', 'oy'],
    examples: [
      { word: 'boy', ipa: '/bɔɪ/', spelling: 'oy' },
      { word: 'coin', ipa: '/kɔɪn/', spelling: 'oi' },
      { word: 'choice', ipa: '/tʃɔɪs/', spelling: 'oi' },
    ],
    minimalPair: { a: 'boy', ipaA: '/bɔɪ/', b: 'buy', ipaB: '/baɪ/' },
  },
  {
    symbol: 'əʊ',
    gaSymbol: 'oʊ',
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi khép',
    keyword: 'GOAT',
    howVi: 'Bắt đầu ở /ə/ với môi dẹt rồi trượt sang /ʊ/, môi tròn dần.',
    trapVi: 'Người học dừng lại ở "ô" tiếng Việt và bỏ chặng trượt, nên go thành "gô". Chặng đầu môi còn dẹt, chỉ chặng sau mới tròn môi.',
    spellings: ['o', 'o_e', 'oa', 'ow', 'oe', 'ough'],
    examples: [
      { word: 'go', ipa: '/ɡəʊ/', spelling: 'o' },
      { word: 'home', ipa: '/həʊm/', spelling: 'o_e' },
      { word: 'know', ipa: '/nəʊ/', spelling: 'ow' },
    ],
    minimalPair: { a: 'coat', ipaA: '/kəʊt/', b: 'caught', ipaB: '/kɔːt/' },
  },
  {
    symbol: 'aʊ',
    gaSymbol: null,
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi khép',
    keyword: 'MOUTH',
    howVi: 'Bắt đầu ở nguyên âm mở phía trước rồi trượt sang /ʊ/, môi tròn dần. Gần với "ao" trong "sao".',
    trapVi: null,
    spellings: ['ou', 'ow'],
    examples: [
      { word: 'now', ipa: '/naʊ/', spelling: 'ow' },
      { word: 'house', ipa: '/haʊs/', spelling: 'ou' },
      { word: 'down', ipa: '/daʊn/', spelling: 'ow' },
    ],
    minimalPair: { a: 'now', ipaA: '/naʊ/', b: 'no', ipaB: '/nəʊ/' },
  },
  {
    symbol: 'ɪə',
    gaSymbol: 'ɪr',
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi hướng tâm',
    keyword: 'NEAR',
    howVi: 'Bắt đầu ở /ɪ/ rồi trượt về /ə/. Miệng mở dần ra giữa.',
    trapVi: 'Chữ r cuối trong here và near bị đọc ra theo mặt chữ. Giọng Anh-Anh dừng ở /ə/, trừ khi từ ngay sau bắt đầu bằng nguyên âm.',
    spellings: ['ear', 'eer', 'ere', 'ier', 'eir'],
    examples: [
      { word: 'here', ipa: '/hɪə/', spelling: 'ere' },
      { word: 'near', ipa: '/nɪə/', spelling: 'ear' },
      { word: 'beer', ipa: '/bɪə/', spelling: 'eer' },
    ],
    minimalPair: { a: 'here', ipaA: '/hɪə/', b: 'hair', ipaB: '/heə/' },
  },
  {
    symbol: 'eə',
    gaSymbol: 'ɛr',
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi hướng tâm',
    keyword: 'SQUARE',
    howVi: 'Bắt đầu ở /e/ rồi trượt về /ə/. Môi giữ dẹt suốt cả hai chặng.',
    trapVi: 'Thiếu chặng trượt về /ə/ thì chair nghe thành "che". Nhiều người bản ngữ nay đọc nó thành một nguyên âm đơn, nhưng vẫn dài hơn /e/.',
    spellings: ['air', 'are', 'ear', 'ere', 'eir'],
    examples: [
      { word: 'hair', ipa: '/heə/', spelling: 'air' },
      { word: 'care', ipa: '/keə/', spelling: 'are' },
      { word: 'where', ipa: '/weə/', spelling: 'ere' },
    ],
    minimalPair: { a: 'hair', ipaA: '/heə/', b: 'here', ipaB: '/hɪə/' },
  },
  {
    symbol: 'ʊə',
    gaSymbol: 'ʊr',
    kind: 'diphthong',
    groupVi: 'Nguyên âm đôi hướng tâm',
    keyword: 'CURE',
    howVi: 'Bắt đầu ở /ʊ/ với môi tròn rồi trượt về /ə/, môi mở ra.',
    trapVi: 'Cặp "ua" tiếng Việt gần giống, nhưng người học gắn thêm chữ r vào sau nó. Âm này đang mất dần, phần lớn người bản ngữ đọc poor thành /pɔː/.',
    spellings: ['oor', 'our', 'ure', 'ur'],
    examples: [
      { word: 'tour', ipa: '/tʊə/', spelling: 'our' },
      { word: 'sure', ipa: '/ʃʊə/', spelling: 'ure' },
      { word: 'pure', ipa: '/pjʊə/', spelling: 'ure' },
    ],
    minimalPair: { a: 'tour', ipaA: '/tʊə/', b: 'tore', ipaB: '/tɔː/' },
  },
  {
    symbol: 'p',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'PEN',
    howVi: 'Ngậm hai môi chặn hơi rồi bật ra. Đầu từ có luồng hơi mạnh kèm theo, trừ khi đứng sau /s/.',
    trapVi: 'Ba phụ âm tắc p, t và c của tiếng Việt đều không bật hơi; chỉ th trong "thi" mang luồng hơi đó, và đây là chỗ gần nhất để mượn cảm giác bật. Thiếu nó thì pen nghe gần như ben, còn cuối từ không mở môi ra nên stop mất phần bật.',
    spellings: ['p', 'pp'],
    examples: [
      { word: 'pen', ipa: '/pen/', spelling: 'p' },
      { word: 'apple', ipa: '/ˈæpl/', spelling: 'pp' },
      { word: 'stop', ipa: '/stɒp/', spelling: 'p' },
    ],
    minimalPair: { a: 'pen', ipaA: '/pen/', b: 'Ben', ipaB: '/ben/' },
  },
  {
    symbol: 'b',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'BOOK',
    howVi: 'Giống /p/ nhưng dây thanh rung và không có luồng hơi bật.',
    trapVi: 'Vị trí cuối từ tiếng Việt chỉ nhận âm vô thanh, nên /b/ trong job bị thay bằng "p" hoặc rụng hẳn.',
    spellings: ['b', 'bb'],
    examples: [
      { word: 'book', ipa: '/bʊk/', spelling: 'b' },
      { word: 'table', ipa: '/ˈteɪbl/', spelling: 'b' },
      { word: 'job', ipa: '/dʒɒb/', spelling: 'b' },
    ],
    minimalPair: { a: 'back', ipaA: '/bæk/', b: 'pack', ipaB: '/pæk/' },
  },
  {
    symbol: 't',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'TEN',
    howVi: 'Đầu lưỡi chạm lợi sau răng cửa trên chặn hơi rồi thả ra. Đầu từ có luồng hơi mạnh kèm theo.',
    trapVi: 'Ở đầu từ, t tiếng Việt không có luồng hơi kèm theo; ở cuối từ, lưỡi chạm lợi rồi dừng luôn nên cat mất phần thả. Giọng Mỹ đọc /t/ giữa hai nguyên âm thành một âm gần "d", như trong water.',
    spellings: ['t', 'tt', 'ed', 'th'],
    examples: [
      { word: 'ten', ipa: '/ten/', spelling: 't' },
      { word: 'letter', ipa: '/ˈletə/', spelling: 'tt' },
      { word: 'cat', ipa: '/kæt/', spelling: 't' },
    ],
    minimalPair: { a: 'ten', ipaA: '/ten/', b: 'den', ipaB: '/den/' },
  },
  {
    symbol: 'd',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'DAY',
    howVi: 'Giống /t/ nhưng dây thanh rung và không có luồng hơi bật. Gần với "đ" tiếng Việt.',
    trapVi: 'Trong tiếng Việt chữ d đọc là /z/ ở miền Bắc và /j/ ở miền Nam chứ không phải "đ", nên day chệch ngay từ mặt chữ. Cuối từ thì /d/ bị bỏ và bad nghe thành bat.',
    spellings: ['d', 'dd', 'ed'],
    examples: [
      { word: 'day', ipa: '/deɪ/', spelling: 'd' },
      { word: 'added', ipa: '/ˈædɪd/', spelling: 'dd' },
      { word: 'red', ipa: '/red/', spelling: 'd' },
    ],
    minimalPair: { a: 'bad', ipaA: '/bæd/', b: 'bat', ipaB: '/bæt/' },
  },
  {
    symbol: 'k',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'CAT',
    howVi: 'Phần sau của lưỡi chạm ngạc mềm chặn hơi rồi thả ra. Đầu từ có luồng hơi mạnh kèm theo.',
    trapVi: 'Đuôi "c" tiếng Việt đóng lại mà không mở ra, nên book nghe cụt. Đầu từ thiếu hơi bật thì cat ngả sang "gát".',
    spellings: ['c', 'k', 'ck', 'ch', 'x trong /ks/', 'que'],
    examples: [
      { word: 'cat', ipa: '/kæt/', spelling: 'c' },
      { word: 'keep', ipa: '/kiːp/', spelling: 'k' },
      { word: 'school', ipa: '/skuːl/', spelling: 'ch' },
    ],
    minimalPair: { a: 'coat', ipaA: '/kəʊt/', b: 'goat', ipaB: '/ɡəʊt/' },
  },
  {
    symbol: 'ɡ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc',
    keyword: 'GO',
    howVi: 'Giống /k/ nhưng dây thanh rung và không có luồng hơi bật. Lưỡi phải chặn hơi hoàn toàn.',
    trapVi: 'Âm viết bằng g trong "gà" là một âm xát, hơi thoát ra liên tục, còn /ɡ/ tiếng Anh phải bịt kín hoàn toàn rồi mới bật.',
    spellings: ['g', 'gg', 'gu', 'gh'],
    examples: [
      { word: 'go', ipa: '/ɡəʊ/', spelling: 'g' },
      { word: 'give', ipa: '/ɡɪv/', spelling: 'g' },
      { word: 'bag', ipa: '/bæɡ/', spelling: 'g' },
    ],
    minimalPair: { a: 'goat', ipaA: '/ɡəʊt/', b: 'coat', ipaB: '/kəʊt/' },
  },
  {
    symbol: 'tʃ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc xát',
    keyword: 'CHAIR',
    howVi: 'Chặn hơi như /t/ rồi thả ra từ từ thành âm xát /ʃ/. Hai động tác nối liền trong một âm.',
    trapVi: '"ch" đầu từ tiếng Việt là âm tắc gọn, không kéo theo phần xát. Ở cuối từ, "ch" trong "sách" là biến thể của âm cuối /k/ chứ không phải /tʃ/, nên watch bị đọc thành "oát".',
    spellings: ['ch', 'tch', 't trong -ture'],
    examples: [
      { word: 'chair', ipa: '/tʃeə/', spelling: 'ch' },
      { word: 'watch', ipa: '/wɒtʃ/', spelling: 'tch' },
      { word: 'teacher', ipa: '/ˈtiːtʃə/', spelling: 'ch' },
    ],
    minimalPair: { a: 'chair', ipaA: '/tʃeə/', b: 'share', ipaB: '/ʃeə/' },
  },
  {
    symbol: 'dʒ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tắc xát',
    keyword: 'JOB',
    howVi: 'Giống /tʃ/ nhưng dây thanh rung suốt cả hai chặng.',
    trapVi: 'Tiếng Việt không ghép một âm tắc với một âm xát thành một đơn vị, nên người học thay bằng "gi" hoặc "d" và job thành "dóp". Đầu lưỡi phải chạm lợi chặn hơi trước khi nhả.',
    spellings: ['j', 'g', 'dge', 'ge', 'd trong -dure'],
    examples: [
      { word: 'job', ipa: '/dʒɒb/', spelling: 'j' },
      { word: 'page', ipa: '/peɪdʒ/', spelling: 'ge' },
      { word: 'bridge', ipa: '/brɪdʒ/', spelling: 'dge' },
    ],
    minimalPair: { a: 'badge', ipaA: '/bædʒ/', b: 'batch', ipaB: '/bætʃ/' },
  },
  {
    symbol: 'f',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'FISH',
    howVi: 'Răng cửa trên chạm môi dưới, đẩy hơi qua khe. Dây thanh không rung. Chính là "ph" tiếng Việt.',
    trapVi: 'Đầu từ đã có sẵn qua "ph", nhưng bảng phụ âm cuối tiếng Việt không nhận /f/, nên leaf và knife rụng âm cuối.',
    spellings: ['f', 'ff', 'ph', 'gh'],
    examples: [
      { word: 'fish', ipa: '/fɪʃ/', spelling: 'f' },
      { word: 'off', ipa: '/ɒf/', spelling: 'ff' },
      { word: 'phone', ipa: '/fəʊn/', spelling: 'ph' },
    ],
    minimalPair: { a: 'fan', ipaA: '/fæn/', b: 'van', ipaB: '/væn/' },
  },
  {
    symbol: 'v',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'VAN',
    howVi: 'Giống /f/ nhưng dây thanh rung.',
    trapVi: 'Trong giọng miền Nam chữ v đọc thành /j/, nên van chệch ngay từ âm đầu. Cuối từ tiếng Việt không có /v/ nên love rụng âm cuối.',
    spellings: ['v', 've', 'f trong of'],
    examples: [
      { word: 'van', ipa: '/væn/', spelling: 'v' },
      { word: 'seven', ipa: '/ˈsevn/', spelling: 'v' },
      { word: 'love', ipa: '/lʌv/', spelling: 've' },
    ],
    minimalPair: { a: 'van', ipaA: '/væn/', b: 'fan', ipaB: '/fæn/' },
  },
  {
    symbol: 'θ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'THINK',
    howVi: 'Đặt đầu lưỡi chạm nhẹ rìa răng cửa trên rồi đẩy hơi qua khe. Dây thanh không rung.',
    trapVi: 'Răng và lưỡi không bao giờ gặp nhau trong tiếng Việt, nên người học đẩy /θ/ về "t" hoặc "th" và think thành "tink".',
    spellings: ['th'],
    examples: [
      { word: 'think', ipa: '/θɪŋk/', spelling: 'th' },
      { word: 'three', ipa: '/θriː/', spelling: 'th' },
      { word: 'bath', ipa: '/bɑːθ/', spelling: 'th' },
    ],
    minimalPair: { a: 'thin', ipaA: '/θɪn/', b: 'tin', ipaB: '/tɪn/' },
  },
  {
    symbol: 'ð',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'THIS',
    howVi: 'Vị trí lưỡi giống /θ/ nhưng dây thanh rung. Đặt tay lên cổ sẽ thấy rung.',
    trapVi: 'Cùng vị trí lưỡi nhưng có rung, âm này bị thay bằng "d" hoặc "z" và this thành "dis". Hai âm th viết giống hệt nhau nên phải nhớ theo từng từ.',
    spellings: ['th'],
    examples: [
      { word: 'this', ipa: '/ðɪs/', spelling: 'th' },
      { word: 'mother', ipa: '/ˈmʌðə/', spelling: 'th' },
      { word: 'with', ipa: '/wɪð/', spelling: 'th' },
    ],
    minimalPair: { a: 'they', ipaA: '/ðeɪ/', b: 'day', ipaB: '/deɪ/' },
  },
  {
    symbol: 's',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'SEE',
    howVi: 'Đầu lưỡi gần lợi trên, đẩy hơi qua một rãnh hẹp. Dây thanh không rung.',
    trapVi: 'Bảng âm cuối tiếng Việt dừng ở /p t k m n ŋ/, nên bus và books rụng /s/. Đây là lý do đuôi số nhiều hay biến mất.',
    spellings: ['s', 'ss', 'c', 'ce', 'se', 'sc'],
    examples: [
      { word: 'see', ipa: '/siː/', spelling: 's' },
      { word: 'cinema', ipa: '/ˈsɪnəmə/', spelling: 'c' },
      { word: 'bus', ipa: '/bʌs/', spelling: 's' },
    ],
    minimalPair: { a: 'sip', ipaA: '/sɪp/', b: 'zip', ipaB: '/zɪp/' },
  },
  {
    symbol: 'z',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'ZOO',
    howVi: 'Giống /s/ nhưng dây thanh rung.',
    trapVi: 'Miền Bắc có /z/ ở đầu từ qua chữ d và gi, nhưng không âm tiết tiếng Việt nào kết thúc bằng nó, nên please và has tụt xuống /s/ hoặc mất hẳn.',
    spellings: ['s', 'z', 'zz', 'se', 'ze'],
    examples: [
      { word: 'zoo', ipa: '/zuː/', spelling: 'z' },
      { word: 'please', ipa: '/pliːz/', spelling: 'se' },
      { word: 'has', ipa: '/hæz/', spelling: 's' },
    ],
    minimalPair: { a: 'zip', ipaA: '/zɪp/', b: 'sip', ipaB: '/sɪp/' },
  },
  {
    symbol: 'ʃ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'SHE',
    howVi: 'Lưỡi lùi về sau so với /s/, môi chúm nhẹ, hơi thoát qua khe rộng hơn.',
    trapVi: 'Ở miền Bắc s và x nhập làm một nên she nghe thành "xi". Cuối từ thì /ʃ/ không có chỗ và fish mất âm cuối.',
    spellings: ['sh', 'ti', 'ci', 'ss', 's', 'ch'],
    examples: [
      { word: 'she', ipa: '/ʃiː/', spelling: 'sh' },
      { word: 'fish', ipa: '/fɪʃ/', spelling: 'sh' },
      { word: 'station', ipa: '/ˈsteɪʃn/', spelling: 'ti' },
    ],
    minimalPair: { a: 'she', ipaA: '/ʃiː/', b: 'sea', ipaB: '/siː/' },
  },
  {
    symbol: 'ʒ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'MEASURE',
    howVi: 'Giống /ʃ/ nhưng dây thanh rung. Không đứng đầu từ tiếng Anh gốc.',
    trapVi: 'Không có chỗ nào trong tiếng Việt cho một âm xát có rung ở vị trí này, nên người học mượn "gi" hoặc /dʒ/ và measure thành "me-giơ".',
    spellings: ['s trước -ure và -ion', 'si', 'g'],
    examples: [
      { word: 'television', ipa: '/ˈtelɪvɪʒn/', spelling: 'si' },
      { word: 'measure', ipa: '/ˈmeʒə/', spelling: 's trước -ure và -ion' },
      { word: 'garage', ipa: '/ˈɡærɑːʒ/', spelling: 'g' },
    ],
    minimalPair: null,
  },
  {
    symbol: 'h',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm xát',
    keyword: 'HOUSE',
    howVi: 'Đẩy hơi ra qua thanh môn, miệng đã ở sẵn vị trí của nguyên âm theo sau.',
    trapVi: null,
    spellings: ['h', 'wh'],
    examples: [
      { word: 'house', ipa: '/haʊs/', spelling: 'h' },
      { word: 'hello', ipa: '/həˈləʊ/', spelling: 'h' },
      { word: 'behind', ipa: '/bɪˈhaɪnd/', spelling: 'h' },
    ],
    minimalPair: { a: 'hat', ipaA: '/hæt/', b: 'cat', ipaB: '/kæt/' },
  },
  {
    symbol: 'm',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm mũi',
    keyword: 'MAN',
    howVi: 'Ngậm hai môi, cho hơi thoát qua mũi. Chính là "m" tiếng Việt.',
    trapVi: null,
    spellings: ['m', 'mm', 'mb'],
    examples: [
      { word: 'man', ipa: '/mæn/', spelling: 'm' },
      { word: 'summer', ipa: '/ˈsʌmə/', spelling: 'mm' },
      { word: 'time', ipa: '/taɪm/', spelling: 'm' },
    ],
    minimalPair: { a: 'mad', ipaA: '/mæd/', b: 'bad', ipaB: '/bæd/' },
  },
  {
    symbol: 'n',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm mũi',
    keyword: 'NO',
    howVi: 'Đầu lưỡi chạm lợi trên chặn hơi trong miệng, hơi thoát qua mũi.',
    trapVi: 'Giọng miền Nam nhập n cuối từ với ng, nên sun nghe thành sung. Đầu lưỡi phải chạm lợi, không lùi về sau.',
    spellings: ['n', 'nn', 'kn', 'gn'],
    examples: [
      { word: 'no', ipa: '/nəʊ/', spelling: 'n' },
      { word: 'dinner', ipa: '/ˈdɪnə/', spelling: 'nn' },
      { word: 'sun', ipa: '/sʌn/', spelling: 'n' },
    ],
    minimalPair: { a: 'sun', ipaA: '/sʌn/', b: 'sung', ipaB: '/sʌŋ/' },
  },
  {
    symbol: 'ŋ',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm mũi',
    keyword: 'SING',
    howVi: 'Chặn hơi bằng phần sau của lưỡi, cho hơi thoát qua mũi. Chính là "ng" trong "ngang".',
    trapVi: 'Sau nguyên âm tròn môi, tiếng Việt khép môi lại như trong "ông". Giữ môi mở, nếu không song nghe thành "soong-m".',
    spellings: ['ng', 'n trước k hoặc g'],
    examples: [
      { word: 'sing', ipa: '/sɪŋ/', spelling: 'ng' },
      { word: 'long', ipa: '/lɒŋ/', spelling: 'ng' },
      { word: 'think', ipa: '/θɪŋk/', spelling: 'n trước k hoặc g' },
    ],
    minimalPair: { a: 'sing', ipaA: '/sɪŋ/', b: 'sin', ipaB: '/sɪn/' },
  },
  {
    symbol: 'l',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tiếp cận',
    keyword: 'LIKE',
    howVi: 'Đầu lưỡi chạm lợi trên, hơi thoát qua hai bên lưỡi. Cuối từ thì phần sau của lưỡi nâng lên, nghe tối hơn.',
    trapVi: 'Vần tiếng Việt không đóng bằng /l/, nên well trôi thành "oeo". Đầu lưỡi phải chạm lợi và giữ nguyên ở đó.',
    spellings: ['l', 'll'],
    examples: [
      { word: 'like', ipa: '/laɪk/', spelling: 'l' },
      { word: 'yellow', ipa: '/ˈjeləʊ/', spelling: 'll' },
      { word: 'well', ipa: '/wel/', spelling: 'll' },
    ],
    minimalPair: { a: 'light', ipaA: '/laɪt/', b: 'right', ipaB: '/raɪt/' },
  },
  {
    symbol: 'r',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tiếp cận',
    keyword: 'RED',
    howVi: 'Lưỡi cong nhẹ lên nhưng không chạm vào đâu cả, môi tròn nhẹ. Lưỡi không rung.',
    trapVi: 'Hai miền chệch theo hai hướng, một bên đọc chữ r thành /z/, một bên cong lưỡi mạnh. /r/ tiếng Anh treo lơ lửng, không chạm vào đâu cả.',
    spellings: ['r', 'rr', 'wr', 'rh'],
    examples: [
      { word: 'red', ipa: '/red/', spelling: 'r' },
      { word: 'arrive', ipa: '/əˈraɪv/', spelling: 'rr' },
      { word: 'write', ipa: '/raɪt/', spelling: 'wr' },
    ],
    minimalPair: { a: 'right', ipaA: '/raɪt/', b: 'light', ipaB: '/laɪt/' },
  },
  {
    symbol: 'w',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tiếp cận',
    keyword: 'WE',
    howVi: 'Môi chúm tròn như sắp đọc /uː/ rồi mở nhanh sang nguyên âm sau nó.',
    trapVi: null,
    spellings: ['w', 'wh', 'u trong qu'],
    examples: [
      { word: 'we', ipa: '/wiː/', spelling: 'w' },
      { word: 'water', ipa: '/ˈwɔːtə/', spelling: 'w' },
      { word: 'question', ipa: '/ˈkwestʃən/', spelling: 'u trong qu' },
    ],
    minimalPair: { a: 'west', ipaA: '/west/', b: 'vest', ipaB: '/vest/' },
  },
  {
    symbol: 'j',
    gaSymbol: null,
    kind: 'consonant',
    groupVi: 'Phụ âm tiếp cận',
    keyword: 'YES',
    howVi: 'Lưỡi đưa lên cao và ra trước như sắp đọc /iː/ rồi trượt nhanh sang nguyên âm sau nó.',
    trapVi: null,
    spellings: ['y', 'i', 'u trong /juː/'],
    examples: [
      { word: 'yes', ipa: '/jes/', spelling: 'y' },
      { word: 'you', ipa: '/juː/', spelling: 'y' },
      { word: 'music', ipa: '/ˈmjuːzɪk/', spelling: 'u trong /juː/' },
    ],
    minimalPair: { a: 'year', ipaA: '/jɪə/', b: 'near', ipaB: '/nɪə/' },
  },
]

export const PRONUNCIATION_NOTES: readonly PronunciationNote[] = [
  {
    id: 'stress',
    titleVi: 'Trọng âm',
    bodyVi:
      'Mỗi từ tiếng Anh có nhiều âm tiết đều có một âm tiết được đọc mạnh hơn, dài hơn và cao giọng hơn. ' +
      'Dấu ˈ trong phiên âm đặt ngay trước âm tiết đó. Đặt sai trọng âm làm người nghe hiểu nhầm nhanh hơn là đọc sai một phụ âm.',
    examples: [
      { en: 'a ˈrecord (danh từ) / to reˈcord (động từ)', vi: 'bản ghi / ghi lại' },
      { en: 'ˈphotograph, phoˈtographer, photoˈgraphic', vi: 'cùng gốc từ, trọng âm chạy theo đuôi' },
    ],
  },
  {
    id: 'weak-forms',
    titleVi: 'Dạng yếu và âm ə',
    bodyVi:
      'Các từ chức năng như a, and, of, to, for, can, was mất nguyên âm gốc khi không mang trọng âm và chỉ còn /ə/. ' +
      'Đây là dạng yếu, và nó là dạng thường gặp hơn trong câu nói. ' +
      'Dạng mạnh chỉ quay lại khi từ đứng cuối câu hoặc được nhấn để đối chiếu: "I can do it" là /kən/, còn "Yes, I can" là /kæn/. ' +
      'Đọc mọi từ theo dạng mạnh làm câu nghe rời rạc và khó theo kịp người bản ngữ.',
    examples: [
      { en: 'a cup of tea /ə ˈkʌp əv ˈtiː/', vi: 'of chỉ còn /əv/' },
      { en: 'I was at home /aɪ wəz ət ˈhəʊm/', vi: 'was và at đều rút về /ə/' },
      { en: 'the apple /ði ˈæpl/, the pear /ðə ˈpeə/', vi: 'the đổi theo âm đầu của từ sau' },
    ],
  },
  {
    id: 'linking',
    titleVi: 'Nối âm',
    bodyVi:
      'Người bản ngữ không tách rời từng từ. Phụ âm cuối của một từ chạy sang nguyên âm đầu của từ sau và thành âm đầu của âm tiết mới. ' +
      'Khi hai nguyên âm gặp nhau, một âm trượt /j/ hoặc /w/ chen vào giữa. ' +
      'Trong giọng Anh-Anh, chữ r cuối từ vốn câm lại được đọc khi từ ngay sau bắt đầu bằng nguyên âm.',
    examples: [
      { en: 'an apple nghe như /ə ˈnæpl/', vi: 'phụ âm cuối chạy sang từ sau' },
      { en: 'go out nghe như /ɡəʊ ˈwaʊt/', vi: 'âm trượt /w/ chen vào giữa hai nguyên âm' },
      { en: 'far away /ˈfɑːr əˈweɪ/', vi: 'chữ r câm trong far được đọc trở lại' },
    ],
  },
  {
    id: 'endings',
    titleVi: 'Đuôi -s và đuôi -ed',
    bodyVi:
      'Đuôi -s có ba cách đọc. Sau các âm rít /s z ʃ ʒ tʃ dʒ/ nó thành một âm tiết riêng /ɪz/; sau phụ âm vô thanh khác nó là /s/; sau mọi âm còn lại nó là /z/. ' +
      'Đuôi -ed cũng có ba cách. Sau /t/ hoặc /d/ nó thành một âm tiết riêng /ɪd/; sau phụ âm vô thanh khác nó là /t/; sau mọi âm còn lại nó là /d/. ' +
      'Chỉ hai dạng /ɪz/ và /ɪd/ thêm một âm tiết, nên books và worked vẫn là một âm tiết chứ không phải hai.',
    examples: [
      { en: 'books /bʊks/, dogs /dɒɡz/, boxes /ˈbɒksɪz/', vi: 'ba cách đọc của đuôi -s' },
      { en: 'worked /wɜːkt/, played /pleɪd/, wanted /ˈwɒntɪd/', vi: 'ba cách đọc của đuôi -ed' },
    ],
  },
  {
    id: 'final-consonants',
    titleVi: 'Phụ âm cuối',
    bodyVi:
      'Tiếng Việt không mở phụ âm cuối ra: đọc "cát" thì lưỡi chạm lợi rồi dừng lại ở đó. Tiếng Anh phải thả ra. ' +
      'Bỏ phụ âm cuối không chỉ làm giọng khó nghe, nó đổi hẳn từ, và mọi đuôi số nhiều hoặc quá khứ biến mất theo. ' +
      'Cụm phụ âm cuối cũng phải đọc đủ, dù tiếng Việt không có cụm nào.',
    examples: [
      { en: 'like /laɪk/ so với lie /laɪ/', vi: 'mất /k/ là đổi từ' },
      { en: 'cold /kəʊld/ so với coal /kəʊl/', vi: 'mất /d/ là đổi từ' },
      { en: 'asked /ɑːskt/, texts /teksts/', vi: 'cụm ba và bốn phụ âm cuối phải đọc đủ' },
    ],
  },
]
