import type { ToeicWordTopic } from '../types'

/** The workplace topics the Listening and Reading test draws on, with the sense each word
 *  carries there: branch is a chi nhánh, not a cành cây. Every word is a headword of the
 *  English dictionary, so each one opens its entry and can be saved from there. */
export const TOEIC_WORD_TOPICS: readonly ToeicWordTopic[] = [
  {
    id: 'office',
    titleVi: 'Văn phòng và họp',
    words: [
      { word: 'agenda', vi: 'chương trình họp' },
      { word: 'memo', vi: 'thông báo nội bộ' },
      { word: 'colleague', vi: 'đồng nghiệp' },
      { word: 'supervisor', vi: 'người quản lý trực tiếp' },
      { word: 'department', vi: 'phòng ban' },
      { word: 'headquarters', vi: 'trụ sở chính' },
      { word: 'branch', vi: 'chi nhánh' },
      { word: 'deadline', vi: 'hạn chót' },
      { word: 'extension', vi: 'số máy lẻ hoặc sự gia hạn' },
      { word: 'stationery', vi: 'văn phòng phẩm' },
      { word: 'handout', vi: 'tài liệu phát tay' },
      { word: 'minutes', vi: 'biên bản cuộc họp' },
      { word: 'reschedule', vi: 'dời lịch' },
      { word: 'postpone', vi: 'hoãn lại' },
    ],
  },
  {
    id: 'hiring',
    titleVi: 'Tuyển dụng và nhân sự',
    words: [
      { word: 'applicant', vi: 'người nộp đơn' },
      { word: 'candidate', vi: 'ứng viên' },
      { word: 'resume', vi: 'sơ yếu lý lịch' },
      { word: 'qualification', vi: 'bằng cấp, điều kiện đáp ứng' },
      { word: 'recruit', vi: 'tuyển dụng' },
      { word: 'vacancy', vi: 'vị trí còn trống' },
      { word: 'personnel', vi: 'nhân sự' },
      { word: 'promotion', vi: 'sự thăng chức hoặc chương trình khuyến mãi' },
      { word: 'salary', vi: 'lương tháng' },
      { word: 'payroll', vi: 'bảng lương' },
      { word: 'benefit', vi: 'phúc lợi' },
      { word: 'orientation', vi: 'buổi hướng dẫn nhân viên mới' },
      { word: 'retire', vi: 'nghỉ hưu' },
      { word: 'reference', vi: 'người giới thiệu, thư giới thiệu' },
    ],
  },
  {
    id: 'finance',
    titleVi: 'Tài chính và kế toán',
    words: [
      { word: 'budget', vi: 'ngân sách' },
      { word: 'invoice', vi: 'hóa đơn đòi tiền' },
      { word: 'receipt', vi: 'biên lai' },
      { word: 'revenue', vi: 'doanh thu' },
      { word: 'profit', vi: 'lợi nhuận' },
      { word: 'expense', vi: 'chi phí' },
      { word: 'reimburse', vi: 'hoàn tiền đã chi' },
      { word: 'deposit', vi: 'tiền đặt cọc, gửi tiền' },
      { word: 'withdraw', vi: 'rút tiền' },
      { word: 'loan', vi: 'khoản vay' },
      { word: 'audit', vi: 'kiểm toán' },
      { word: 'estimate', vi: 'bản ước tính giá' },
      { word: 'quarter', vi: 'quý' },
      { word: 'fiscal', vi: 'thuộc năm tài chính' },
    ],
  },
  {
    id: 'sales',
    titleVi: 'Bán hàng và marketing',
    words: [
      { word: 'client', vi: 'khách hàng' },
      { word: 'discount', vi: 'giảm giá' },
      { word: 'refund', vi: 'hoàn tiền' },
      { word: 'warranty', vi: 'bảo hành' },
      { word: 'merchandise', vi: 'hàng hóa' },
      { word: 'inventory', vi: 'hàng tồn kho' },
      { word: 'advertisement', vi: 'quảng cáo' },
      { word: 'campaign', vi: 'chiến dịch' },
      { word: 'survey', vi: 'khảo sát' },
      { word: 'competitor', vi: 'đối thủ cạnh tranh' },
      { word: 'launch', vi: 'ra mắt sản phẩm' },
      { word: 'brochure', vi: 'tờ giới thiệu' },
      { word: 'quote', vi: 'báo giá' },
      { word: 'subscription', vi: 'gói đăng ký dài hạn' },
    ],
  },
  {
    id: 'shipping',
    titleVi: 'Sản xuất và giao hàng',
    words: [
      { word: 'shipment', vi: 'lô hàng' },
      { word: 'warehouse', vi: 'nhà kho' },
      { word: 'supplier', vi: 'nhà cung cấp' },
      { word: 'manufacture', vi: 'sản xuất' },
      { word: 'assemble', vi: 'lắp ráp' },
      { word: 'equipment', vi: 'thiết bị' },
      { word: 'defective', vi: 'bị lỗi' },
      { word: 'package', vi: 'bưu kiện' },
      { word: 'courier', vi: 'dịch vụ chuyển phát' },
      { word: 'freight', vi: 'hàng hóa vận chuyển, cước vận chuyển' },
      { word: 'dispatch', vi: 'gửi đi' },
      { word: 'track', vi: 'theo dõi đơn hàng' },
      { word: 'fragile', vi: 'dễ vỡ' },
      { word: 'vendor', vi: 'người bán, nhà cung cấp' },
    ],
  },
  {
    id: 'travel',
    titleVi: 'Đi lại và công tác',
    words: [
      { word: 'itinerary', vi: 'lịch trình' },
      { word: 'reservation', vi: 'sự đặt chỗ' },
      { word: 'accommodation', vi: 'chỗ ở' },
      { word: 'departure', vi: 'sự khởi hành' },
      { word: 'destination', vi: 'điểm đến' },
      { word: 'luggage', vi: 'hành lý' },
      { word: 'fare', vi: 'giá vé' },
      { word: 'terminal', vi: 'nhà ga' },
      { word: 'boarding', vi: 'việc lên máy bay' },
      { word: 'delay', vi: 'sự chậm trễ' },
      { word: 'commute', vi: 'đi làm hằng ngày' },
      { word: 'shuttle', vi: 'xe đưa đón' },
      { word: 'aisle', vi: 'lối đi giữa các hàng ghế' },
      { word: 'customs', vi: 'hải quan' },
    ],
  },
  {
    id: 'events',
    titleVi: 'Nhà hàng và sự kiện',
    words: [
      { word: 'cater', vi: 'cung cấp đồ ăn cho sự kiện' },
      { word: 'banquet', vi: 'tiệc lớn' },
      { word: 'reception', vi: 'quầy lễ tân, tiệc chiêu đãi' },
      { word: 'venue', vi: 'địa điểm tổ chức' },
      { word: 'attendee', vi: 'người tham dự' },
      { word: 'registration', vi: 'sự đăng ký' },
      { word: 'refreshment', vi: 'đồ ăn nhẹ và nước uống, thường dùng số nhiều' },
      { word: 'beverage', vi: 'đồ uống' },
      { word: 'complimentary', vi: 'miễn phí' },
      { word: 'keynote', vi: 'bài phát biểu chính' },
      { word: 'exhibition', vi: 'triển lãm' },
      { word: 'host', vi: 'đăng cai, dẫn chương trình' },
    ],
  },
  {
    id: 'property',
    titleVi: 'Nhà cửa và bảo trì',
    words: [
      { word: 'lease', vi: 'hợp đồng thuê' },
      { word: 'tenant', vi: 'người thuê' },
      { word: 'landlord', vi: 'chủ nhà' },
      { word: 'renovate', vi: 'cải tạo' },
      { word: 'maintenance', vi: 'bảo trì' },
      { word: 'repair', vi: 'sửa chữa' },
      { word: 'utility', vi: 'điện nước' },
      { word: 'plumber', vi: 'thợ sửa ống nước' },
      { word: 'contractor', vi: 'nhà thầu' },
      { word: 'facility', vi: 'cơ sở vật chất' },
      { word: 'inspect', vi: 'kiểm tra' },
      { word: 'premises', vi: 'khuôn viên, trụ sở' },
    ],
  },
  {
    id: 'health',
    titleVi: 'Sức khỏe',
    words: [
      { word: 'appointment', vi: 'cuộc hẹn' },
      { word: 'prescription', vi: 'đơn thuốc' },
      { word: 'pharmacy', vi: 'nhà thuốc' },
      { word: 'clinic', vi: 'phòng khám' },
      { word: 'insurance', vi: 'bảo hiểm' },
      { word: 'physician', vi: 'bác sĩ' },
      { word: 'checkup', vi: 'lần khám sức khỏe định kỳ' },
      { word: 'symptom', vi: 'triệu chứng' },
    ],
  },
  {
    id: 'technology',
    titleVi: 'Công nghệ',
    words: [
      { word: 'install', vi: 'cài đặt' },
      { word: 'upgrade', vi: 'nâng cấp' },
      { word: 'device', vi: 'thiết bị' },
      { word: 'software', vi: 'phần mềm' },
      { word: 'technician', vi: 'kỹ thuật viên' },
      { word: 'malfunction', vi: 'trục trặc' },
      { word: 'password', vi: 'mật khẩu' },
      { word: 'attachment', vi: 'file đính kèm' },
      { word: 'download', vi: 'tải xuống' },
      { word: 'compatible', vi: 'tương thích' },
    ],
  },
  {
    id: 'contracts',
    titleVi: 'Hợp đồng và quy định',
    words: [
      { word: 'contract', vi: 'hợp đồng' },
      { word: 'agreement', vi: 'thỏa thuận' },
      { word: 'negotiate', vi: 'đàm phán' },
      { word: 'terms', vi: 'điều khoản' },
      { word: 'expire', vi: 'hết hạn' },
      { word: 'renew', vi: 'gia hạn' },
      { word: 'comply', vi: 'tuân thủ' },
      { word: 'regulation', vi: 'quy định' },
      { word: 'policy', vi: 'chính sách' },
      { word: 'approve', vi: 'phê duyệt' },
      { word: 'signature', vi: 'chữ ký' },
      { word: 'confidential', vi: 'bảo mật' },
    ],
  },
  {
    id: 'common',
    titleVi: 'Động từ và tính từ gặp ở mọi chủ đề',
    words: [
      { word: 'submit', vi: 'nộp' },
      { word: 'confirm', vi: 'xác nhận' },
      { word: 'attach', vi: 'đính kèm' },
      { word: 'enclose', vi: 'gửi kèm trong thư' },
      { word: 'implement', vi: 'triển khai' },
      { word: 'relocate', vi: 'chuyển địa điểm' },
      { word: 'available', vi: 'có sẵn, rảnh' },
      { word: 'eligible', vi: 'đủ điều kiện' },
      { word: 'mandatory', vi: 'bắt buộc' },
      { word: 'tentative', vi: 'tạm thời, chưa chốt' },
      { word: 'reliable', vi: 'đáng tin cậy' },
      { word: 'prior', vi: 'trước đó' },
      { word: 'upcoming', vi: 'sắp tới' },
      { word: 'outstanding', vi: 'xuất sắc hoặc còn nợ chưa trả' },
    ],
  },
]
