import type { ToeicQuestion } from '../types'

/** One Part 5 set: 30 items, the length of the part on the real test. Written for this
 *  project, not taken from ETS material or any book. */
export const TOEIC_PRACTICE: readonly ToeicQuestion[] = [
  {
    id: 'p5-01',
    sentence: 'Applicants for the sales position should have a strong ------- to customer service.',
    options: ['commit', 'committed', 'committing', 'commitment'],
    answer: 3,
    skillVi: 'Từ loại',
    whyVi: 'Sau mạo từ a và tính từ strong cần một danh từ. Commitment to là sự cam kết với một việc.',
    vi: 'Ứng viên cho vị trí bán hàng cần có sự cam kết cao với việc chăm sóc khách hàng.',
  },
  {
    id: 'p5-02',
    sentence: 'The shipment of office chairs ------- to the Denver branch yesterday afternoon.',
    options: ['delivered', 'was delivered', 'is delivering', 'has been delivered'],
    answer: 1,
    skillVi: 'Thì và dạng động từ',
    whyVi: 'Lô hàng không tự giao nên động từ ở dạng bị động. Yesterday afternoon là mốc quá khứ cụ thể nên dùng quá khứ đơn, không dùng hiện tại hoàn thành.',
    vi: 'Lô ghế văn phòng đã được giao đến chi nhánh Denver vào chiều hôm qua.',
  },
  {
    id: 'p5-03',
    sentence: '------- the heavy rain, the outdoor product launch went ahead as planned.',
    options: ['Despite', 'Although', 'Because', 'However'],
    answer: 0,
    skillVi: 'Giới từ và liên từ',
    whyVi: 'Despite đứng trước một cụm danh từ, ở đây là the heavy rain. Although và because phải đi với một mệnh đề có chủ ngữ và động từ.',
    vi: 'Dù trời mưa lớn, buổi ra mắt sản phẩm ngoài trời vẫn diễn ra như kế hoạch.',
  },
  {
    id: 'p5-04',
    sentence: 'Due to high demand, the restaurant recommends that guests make a ------- at least two days in advance.',
    options: ['preservation', 'observation', 'reservation', 'conservation'],
    answer: 2,
    skillVi: 'Từ vựng',
    whyVi: 'Make a reservation là đặt chỗ trước. Ba từ còn lại có hình thức gần giống nhưng nghĩa là bảo quản, quan sát và bảo tồn.',
    vi: 'Do lượng khách đông, nhà hàng khuyến nghị khách đặt chỗ trước ít nhất hai ngày.',
  },
  {
    id: 'p5-05',
    sentence: 'The new software allows staff to track customer orders more ------- than the old version did.',
    options: ['efficient', 'efficiency', 'efficiently', 'efficiencies'],
    answer: 2,
    skillVi: 'Từ loại',
    whyVi: 'Cần một trạng từ để bổ nghĩa cho động từ track. More efficiently là dạng so sánh hơn của trạng từ efficiently.',
    vi: 'Phần mềm mới giúp nhân viên theo dõi đơn hàng của khách hiệu quả hơn phiên bản cũ.',
  },
  {
    id: 'p5-06',
    sentence: 'Customers who wish to cancel ------- subscriptions should contact the billing department.',
    options: ['their', 'they', 'them', 'theirs'],
    answer: 0,
    skillVi: 'Đại từ',
    whyVi: 'Trước danh từ subscriptions cần tính từ sở hữu their. Theirs là đại từ sở hữu, đứng một mình và không đi kèm danh từ.',
    vi: 'Khách hàng muốn hủy gói đăng ký của mình cần liên hệ bộ phận thanh toán.',
  },
  {
    id: 'p5-07',
    sentence: 'The warehouse was ------- closed for two days while the new shelves were installed.',
    options: ['temporary', 'temporarily', 'temporariness', 'temporaries'],
    answer: 1,
    skillVi: 'Từ loại',
    whyVi: 'Giữa was và quá khứ phân từ closed cần một trạng từ. Temporarily nghĩa là tạm thời.',
    vi: 'Nhà kho tạm đóng cửa hai ngày trong lúc lắp kệ mới.',
  },
  {
    id: 'p5-08',
    sentence: 'Each of the conference rooms on the third floor ------- a projector and a video conferencing screen.',
    options: ['have', 'having', 'to have', 'has'],
    answer: 3,
    skillVi: 'Thì và dạng động từ',
    whyVi: 'Chủ ngữ là each, dù theo sau là danh từ số nhiều, nên động từ chia số ít. Vì vậy dùng has.',
    vi: 'Mỗi phòng họp ở tầng ba đều có một máy chiếu và một màn hình họp trực tuyến.',
  },
  {
    id: 'p5-09',
    sentence: 'All expense reports must be submitted ------- 5 P.M. on Friday.',
    options: ['until', 'within', 'since', 'by'],
    answer: 3,
    skillVi: 'Giới từ và liên từ',
    whyVi: 'By chỉ hạn chót, việc phải xong trước hoặc đúng lúc đó. Until dùng cho việc kéo dài liên tục đến một thời điểm, không dùng cho hành động nộp một lần.',
    vi: 'Mọi báo cáo chi phí phải được nộp trước 5 giờ chiều thứ Sáu.',
  },
  {
    id: 'p5-10',
    sentence: 'The board of directors will ------- a final decision on the merger next Tuesday.',
    options: ['make', 'do', 'put', 'set'],
    answer: 0,
    skillVi: 'Từ vựng',
    whyVi: 'Danh từ decision đi với động từ make: make a decision. Tiếng Anh không nói do a decision, put a decision hay set a decision.',
    vi: 'Hội đồng quản trị sẽ đưa ra quyết định cuối cùng về việc sáp nhập vào thứ Ba tới.',
  },
  {
    id: 'p5-11',
    sentence: 'The new laptop models, ------- were released in March, have sold better than expected.',
    options: ['who', 'which', 'what', 'whose'],
    answer: 1,
    skillVi: 'Mệnh đề quan hệ',
    whyVi: 'Mệnh đề quan hệ sau dấu phẩy bổ nghĩa cho vật nên dùng which. Who chỉ dùng cho người, còn what không đứng sau danh từ.',
    vi: 'Các mẫu laptop mới ra mắt vào tháng Ba đã bán chạy hơn dự kiến.',
  },
  {
    id: 'p5-12',
    sentence: 'Ms. Tanaka was praised for her ------- handling of a difficult customer complaint.',
    options: ['profession', 'professionally', 'professional', 'professionalism'],
    answer: 2,
    skillVi: 'Từ loại',
    whyVi: 'Giữa tính từ sở hữu her và danh từ handling cần một tính từ. Handling có of theo sau nên là danh từ, vì vậy không dùng trạng từ.',
    vi: 'Bà Tanaka được khen vì đã xử lý chuyên nghiệp một lời phàn nàn khó của khách hàng.',
  },
  {
    id: 'p5-13',
    sentence: 'The new delivery service is almost twice as ------- as the previous one.',
    options: ['fast', 'faster', 'fastest', 'fastly'],
    answer: 0,
    skillVi: 'So sánh',
    whyVi: 'So sánh bằng dùng as + tính từ nguyên dạng + as, twice đứng trước để chỉ gấp đôi. Fast vừa là tính từ vừa là trạng từ, không có dạng fastly.',
    vi: 'Dịch vụ giao hàng mới nhanh gần gấp đôi dịch vụ trước.',
  },
  {
    id: 'p5-14',
    sentence: 'Ms. Chen ------- in the accounting department since she joined the company in 2019.',
    options: ['works', 'worked', 'is working', 'has worked'],
    answer: 3,
    skillVi: 'Thì và dạng động từ',
    whyVi: 'Since cộng một mốc quá khứ chỉ việc bắt đầu từ lúc đó và còn kéo dài đến nay. Vì vậy dùng hiện tại hoàn thành has worked.',
    vi: 'Bà Chen làm việc ở phòng kế toán từ khi vào công ty năm 2019.',
  },
  {
    id: 'p5-15',
    sentence: 'To ensure -------, all visitors must sign in at the front desk and wear a badge.',
    options: ['secure', 'security', 'securely', 'secured'],
    answer: 1,
    skillVi: 'Từ loại',
    whyVi: 'Sau động từ ensure cần một danh từ làm tân ngữ. Security là an ninh, còn secure là tính từ hoặc động từ.',
    vi: 'Để bảo đảm an ninh, mọi khách đến phải đăng ký tại quầy lễ tân và đeo thẻ ra vào.',
  },
  {
    id: 'p5-16',
    sentence: 'Visitors are asked to switch off their mobile phones ------- the presentation.',
    options: ['while', 'when', 'during', 'as'],
    answer: 2,
    skillVi: 'Giới từ và liên từ',
    whyVi: 'During đứng trước một danh từ, ở đây là the presentation. While và when cần một mệnh đề theo sau.',
    vi: 'Khách tham dự được yêu cầu tắt điện thoại di động trong suốt buổi thuyết trình.',
  },
  {
    id: 'p5-17',
    sentence: 'The job offer includes a competitive salary and generous -------, such as health insurance and paid leave.',
    options: ['profits', 'benefits', 'incomes', 'savings'],
    answer: 1,
    skillVi: 'Từ vựng',
    whyVi: 'Benefits trong tuyển dụng là phúc lợi như bảo hiểm và ngày nghỉ có lương. Profits là lợi nhuận của công ty, không phải thứ người lao động nhận.',
    vi: 'Lời mời làm việc gồm mức lương cạnh tranh cùng các phúc lợi tốt như bảo hiểm y tế và nghỉ phép có lương.',
  },
  {
    id: 'p5-18',
    sentence: 'Mr. Alvarez will ------- the quarterly budget meeting while the director is away.',
    options: ['lead', 'leader', 'leading', 'leadership'],
    answer: 0,
    skillVi: 'Từ loại',
    whyVi: 'Sau động từ khuyết thiếu will cần động từ nguyên mẫu. Lead ở đây là chủ trì.',
    vi: 'Ông Alvarez sẽ chủ trì cuộc họp ngân sách quý trong thời gian giám đốc đi vắng.',
  },
  {
    id: 'p5-19',
    sentence: 'Mr. Park prefers to review important contracts ------- rather than leave the task to his assistant.',
    options: ['he', 'him', 'himself', 'his'],
    answer: 2,
    skillVi: 'Đại từ',
    whyVi: 'Đại từ phản thân himself đứng cuối để nhấn mạnh chính người đó tự làm. Câu đối lập với việc giao cho trợ lý nên cần nghĩa tự mình.',
    vi: 'Ông Park thích tự mình xem xét các hợp đồng quan trọng hơn là giao việc đó cho trợ lý.',
  },
  {
    id: 'p5-20',
    sentence: 'If the contract ------- by Friday, construction can start the following Monday.',
    options: ['signs', 'will sign', 'signed', 'is signed'],
    answer: 3,
    skillVi: 'Thì và dạng động từ',
    whyVi: 'Câu điều kiện loại 1 dùng thì hiện tại sau if, không dùng will. Hợp đồng không tự ký nên cần bị động is signed.',
    vi: 'Nếu hợp đồng được ký trước thứ Sáu, việc thi công có thể bắt đầu vào thứ Hai tuần sau.',
  },
  {
    id: 'p5-21',
    sentence: 'The marketing team has made ------- progress on the spring campaign.',
    options: ['considerable', 'consider', 'considerably', 'consideration'],
    answer: 0,
    skillVi: 'Từ loại',
    whyVi: 'Trước danh từ progress cần một tính từ. Make considerable progress là đạt tiến triển đáng kể.',
    vi: 'Nhóm marketing đã đạt tiến triển đáng kể trong chiến dịch mùa xuân.',
  },
  {
    id: 'p5-22',
    sentence: 'The flight to Singapore was delayed ------- a technical problem with the aircraft.',
    options: ['because', 'due to', 'since', 'so that'],
    answer: 1,
    skillVi: 'Giới từ và liên từ',
    whyVi: 'Due to đi với cụm danh từ, ở đây là a technical problem. Because phải thêm of mới đứng được trước danh từ.',
    vi: 'Chuyến bay đến Singapore bị hoãn do máy bay gặp sự cố kỹ thuật.',
  },
  {
    id: 'p5-23',
    sentence: 'The candidate ------- application impressed the committee most will be invited to a second interview.',
    options: ['who', 'whom', 'which', 'whose'],
    answer: 3,
    skillVi: 'Mệnh đề quan hệ',
    whyVi: 'Whose chỉ sự sở hữu và đứng ngay trước danh từ application. Hồ sơ là của ứng viên nên dùng whose.',
    vi: 'Ứng viên có hồ sơ gây ấn tượng nhất với hội đồng sẽ được mời phỏng vấn vòng hai.',
  },
  {
    id: 'p5-24',
    sentence: "All employees are required to ------- with the company's new data protection policy.",
    options: ['obey', 'follow', 'comply', 'respect'],
    answer: 2,
    skillVi: 'Từ vựng',
    whyVi: 'Comply luôn đi với with: comply with a policy là tuân thủ quy định. Follow, obey và respect nhận tân ngữ trực tiếp, không đi với with.',
    vi: 'Mọi nhân viên bắt buộc phải tuân thủ chính sách bảo vệ dữ liệu mới của công ty.',
  },
  {
    id: 'p5-25',
    sentence: "The hotel's rooftop restaurant has become ------- popular with business travelers.",
    options: ['increasingly', 'increase', 'increasing', 'increased'],
    answer: 0,
    skillVi: 'Từ loại',
    whyVi: 'Trước tính từ popular cần một trạng từ để bổ nghĩa. Increasingly popular là ngày càng được ưa chuộng.',
    vi: 'Nhà hàng trên sân thượng của khách sạn ngày càng được khách đi công tác ưa chuộng.',
  },
  {
    id: 'p5-26',
    sentence: 'Of the three hotels we contacted, the Grand Plaza offered the ------- rates.',
    options: ['low', 'lower', 'lowest', 'most low'],
    answer: 2,
    skillVi: 'So sánh',
    whyVi: 'Có ba khách sạn để so sánh nên dùng so sánh nhất the lowest. So sánh hơn lower chỉ dùng khi so hai đối tượng.',
    vi: 'Trong ba khách sạn đã liên hệ, Grand Plaza đưa ra mức giá thấp nhất.',
  },
  {
    id: 'p5-27',
    sentence: 'By the time the new manager arrives next week, the team ------- the annual report.',
    options: ['completes', 'will have completed', 'has completed', 'completed'],
    answer: 1,
    skillVi: 'Thì và dạng động từ',
    whyVi: 'By the time với một mốc tương lai cho biết việc sẽ xong trước mốc đó, nên dùng tương lai hoàn thành. Mệnh đề sau by the time vẫn chia hiện tại đơn arrives.',
    vi: 'Trước khi quản lý mới đến vào tuần sau, nhóm sẽ hoàn tất báo cáo thường niên.',
  },
  {
    id: 'p5-28',
    sentence: 'The new printer is not only faster ------- more energy-efficient than the old one.',
    options: ['and', 'or', 'but also', 'as well'],
    answer: 2,
    skillVi: 'Giới từ và liên từ',
    whyVi: 'Not only luôn đi thành cặp với but also. And hoặc as well không ghép được với not only.',
    vi: 'Máy in mới không chỉ nhanh hơn mà còn tiết kiệm điện hơn máy cũ.',
  },
  {
    id: 'p5-29',
    sentence: 'Please note that the ------- of the parking garage will begin next Monday.',
    options: ['renovate', 'renovated', 'renovates', 'renovation'],
    answer: 3,
    skillVi: 'Từ loại',
    whyVi: 'Sau mạo từ the và trước of cần một danh từ. Renovation là việc cải tạo.',
    vi: 'Lưu ý rằng việc cải tạo nhà để xe sẽ bắt đầu vào thứ Hai tới.',
  },
  {
    id: 'p5-30',
    sentence: 'The warranty ------- all repairs for the first two years after purchase.',
    options: ['covers', 'pays', 'guards', 'holds'],
    answer: 0,
    skillVi: 'Từ vựng',
    whyVi: 'Cover là chi trả trong phạm vi bảo hành hoặc bảo hiểm: the warranty covers repairs. Pay phải có for mới đi được với repairs, còn guard và hold không mang nghĩa này.',
    vi: 'Chế độ bảo hành chi trả mọi lần sửa chữa trong hai năm đầu kể từ ngày mua.',
  },
]
