// Builds English word families from Open English WordNet (CC BY 4.0) and writes the SQL that
// loads them as `family` rows of lex.lex_relations, source `oewn`.
//   curl -LO https://github.com/globalwordnet/english-wordnet/releases/download/2025-edition/english-wordnet-2025-plus.xml.gz
//   node scripts/wordFamily/build.mjs english-wordnet-2025-plus.xml.gz out.sql [word ...]
// Words given after out.sql are printed with their families, to read before loading. The SQL
// replaces every row of the previous run, so a rerun after a data load is safe.
import { readFileSync, writeFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { createJiti } from 'jiti'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const jiti = createJiti(import.meta.url, { alias: { '@': root } })
const { wordFamilies } = await jiti.import('@/lib/dictionary/wordFamily.ts')

const [xmlPath, outPath, ...samples] = process.argv.slice(2)
if (!outPath) throw new Error('usage: build.mjs english-wordnet.xml.gz out.sql [word ...]')

const xml = gunzipSync(readFileSync(xmlPath)).toString('utf8')
const KINDS = new Set(['derivation', 'pertainym', 'participle', 'antonym'])
const lemmaOfSense = new Map()
const pending = []
let lemma = null
for (const line of xml.split('\n')) {
  const l = /<Lemma writtenForm="([^"]*)"/.exec(line)
  if (l) { lemma = l[1].replace(/&apos;/g, "'").replace(/&amp;/g, '&'); continue }
  const s = /<Sense id="([^"]+)"/.exec(line)
  if (s) { lemmaOfSense.set(s[1], lemma); pending.push({ sense: s[1] }); continue }
  const r = /<SenseRelation relType="([a-z_]+)" target="([^"]+)"/.exec(line)
  if (r && KINDS.has(r[1])) pending.push({ kind: r[1], target: r[2] })
}
const links = []
let from = null
for (const p of pending) {
  if (p.sense) { from = lemmaOfSense.get(p.sense); continue }
  const to = lemmaOfSense.get(p.target)
  if (from && to) links.push({ a: from, b: to, kind: p.kind })
}

const families = wordFamilies(links)
const sizes = [...families.values()].map((f) => f.length)
console.log({
  links: links.length,
  words: families.size,
  members: sizes.reduce((a, b) => a + b, 0),
  capped: sizes.filter((n) => n >= 12).length,
})
for (const w of samples) console.log(w, '=>', (families.get(w) ?? []).join(', '))

const rows = [...families].flatMap(([word, members]) => members.map((m, i) => `${word}\t${m}\t${i}`))
writeFileSync(outPath, `-- Generated by scripts/wordFamily/build.mjs from Open English WordNet 2025 Plus.
set statement_timeout = '600s';
begin;
create temp table fam (headword text, member text, rank int) on commit drop;
copy fam from stdin;
${rows.join('\n')}
\\.
delete from lex.lex_relations where source_id = 'oewn' and relation_type = 'family';
-- Inflections (deciding, form_of decide) are the word itself, not its family.
insert into lex.lex_relations (entry_id, related_entry_id, related_text, relation_type, source_id)
select a.id, b.id, b.headword, 'family', 'oewn'
from fam
join lex.entries a on a.lang = 'en' and a.entry_type = 'word' and a.headword = fam.headword and a.form_of is null
join lex.entries b on b.lang = 'en' and b.entry_type = 'word' and b.headword = fam.member and b.form_of is null
order by a.id, fam.rank;
commit;
`)
console.log('rows', rows.length, 'written to', outPath)
