// Ranks every English synonym and antonym of lex.lex_relations (migration 0197) and writes the
// SQL that stores the rank. A pair Open English WordNet (CC BY 4.0) also makes comes first: two
// members of one synset or of two synsets it marks similar (big and huge), or two senses it marks
// antonyms. Then a single word before a phrase, then the more frequent word.
//   node scripts/relationRank/build.mjs english-wordnet-2025-plus.xml.gz out.sql [word ...]
// Words given after out.sql are printed with the WordNet pairs found for them. A rerun
// recomputes every rank, so it is safe after a data load.
import { readFileSync, writeFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'

const [xmlPath, outPath, ...samples] = process.argv.slice(2)
if (!outPath) throw new Error('usage: build.mjs english-wordnet.xml.gz out.sql [word ...]')

const xml = gunzipSync(readFileSync(xmlPath)).toString('utf8')
const decode = (s) => s.replace(/&apos;/g, "'").replace(/&quot;/g, '"').replace(/&amp;/g, '&')
const lemmaOfEntry = new Map()
const lemmaOfSense = new Map()
const antonyms = []
let lemma = null
let entry = null
let sense = null
let synset = null
const synsets = new Map()
const similar = []
for (const line of xml.split('\n')) {
  const e = /<LexicalEntry id="([^"]+)"/.exec(line)
  if (e) { entry = e[1]; continue }
  const l = /<Lemma writtenForm="([^"]*)"/.exec(line)
  if (l) { lemma = decode(l[1]); lemmaOfEntry.set(entry, lemma); continue }
  const s = /<Sense id="([^"]+)"/.exec(line)
  if (s) { sense = s[1]; lemmaOfSense.set(sense, lemma); continue }
  const a = /<SenseRelation relType="antonym" target="([^"]+)"/.exec(line)
  if (a) { antonyms.push([sense, a[1]]); continue }
  const y = /<Synset id="([^"]+)"[^>]* members="([^"]+)"/.exec(line)
  if (y) { synset = y[1]; synsets.set(synset, y[2].split(' ')); continue }
  const m = /<SynsetRelation relType="similar" target="([^"]+)"/.exec(line)
  if (m) similar.push([synset, m[1]])
}

const pairs = new Set()
const add = (a, b, kind) => {
  if (!a || !b || a.toLowerCase() === b.toLowerCase()) return
  pairs.add(`${a}\t${b.toLowerCase()}\t${kind}`)
  pairs.add(`${b}\t${a.toLowerCase()}\t${kind}`)
}
const lemmasOf = (id) => (synsets.get(id) ?? []).map((m) => lemmaOfEntry.get(m)).filter(Boolean)
for (const id of synsets.keys()) {
  const lemmas = lemmasOf(id)
  for (let i = 0; i < lemmas.length; i++) for (let j = i + 1; j < lemmas.length; j++) add(lemmas[i], lemmas[j], 'synonym')
}
for (const [a, b] of similar) for (const x of lemmasOf(a)) for (const y of lemmasOf(b)) add(x, y, 'synonym')
for (const [from, to] of antonyms) add(lemmaOfSense.get(from), lemmaOfSense.get(to), 'antonym')

const rows = [...pairs]
console.log({ synsets: synsets.size, similar: similar.length, pairs: rows.length })
for (const w of samples) {
  console.log(w, '=>', rows.filter((r) => r.startsWith(`${w}\t`)).map((r) => r.split('\t').slice(1).join(':')).join(', '))
}

writeFileSync(outPath, `-- Generated by scripts/relationRank/build.mjs from Open English WordNet 2025 Plus.
set statement_timeout = '900s';
begin;
create temp table oewn_pair (headword text, related text, kind text) on commit drop;
copy oewn_pair from stdin;
${rows.join('\n')}
\\.
create index on oewn_pair (headword, related, kind);
analyze oewn_pair;
update lex.lex_relations r set rank = x.rn
from (
  select r.id, least(row_number() over (
    partition by r.entry_id, r.relation_type
    order by (o.headword is not null) desc, (strpos(r.related_text, ' ') = 0) desc,
             t.frequency_rank nulls last, r.related_text, r.id), 32767) as rn
  from lex.lex_relations r
  join lex.entries e on e.id = r.entry_id and e.lang = 'en'
  left join lex.entries t on t.id = r.related_entry_id
  left join oewn_pair o on o.headword = e.headword and o.related = lower(r.related_text) and o.kind = r.relation_type
  where r.relation_type in ('synonym', 'antonym')
) x
where x.id = r.id and r.rank is distinct from x.rn;
commit;
`)
console.log('written to', outPath)
