"""Writes lib/theory/en/toeicList.ts from the TOEIC Service List 1.2 (Browne and Culligan,
CC BY-SA 4.0, https://www.newgeneralservicelist.com/toeic-service-list).

usage: python3 scripts/toeicList/build.py <dir>
<dir> holds TSL_12_stats.csv and TSL_12_definitions.xlsx as downloaded from that page."""
import csv, html, io, json, re, sys, zipfile

src = sys.argv[1]
out = 'lib/theory/en/toeicList.ts'

# The stats file is Latin-1 ("résumé"); its order is the list's frequency rank.
rows = list(csv.DictReader(io.open(f'{src}/TSL_12_stats.csv', encoding='latin-1')))
words = [r['Word'].strip() for r in sorted(rows, key=lambda r: int(r['TSL Rank']))]

# An .xlsx is a zip of XML: shared strings plus one sheet of (word, definition) rows.
z = zipfile.ZipFile(f'{src}/TSL_12_definitions.xlsx')
strings = [html.unescape(re.sub(r'<[^>]+>', '', s))
           for s in re.findall(r'<si>(.*?)</si>', z.read('xl/sharedStrings.xml').decode(), re.S)]
definitions = {}
# Exact match only: folding "résumé" to "resume" would give it the verb's definition.
key = lambda w: w.strip().lower()
for row in re.findall(r'<row[^>]*>(.*?)</row>', z.read('xl/worksheets/sheet1.xml').decode(), re.S)[1:]:
    cells = [strings[int(v)] if 't="s"' in a else v
             for a, v in re.findall(r'<c ([^>]*)>(?:<f>.*?</f>)?<v>(.*?)</v></c>', row)]
    if len(cells) >= 2:
        definitions[key(cells[0])] = re.sub(r'\s+', ' ', cells[1]).strip()

missing = [w for w in words if key(w) not in definitions]
lines = ',\n'.join(f'  [{json.dumps(w, ensure_ascii=False)}, {json.dumps(definitions.get(key(w)), ensure_ascii=False)}]'
                   for w in words)
with open(out, 'w', encoding='utf-8') as fh:
    fh.write(f'''// Generated by scripts/toeicList/build.py. Do not edit by hand.

/** TOEIC Service List 1.2 by Browne and Culligan, CC BY-SA 4.0: the {len(words):,} words that, beside the
 *  2,809 of the New General Service List, cover 98.5% of TOEIC tests. In frequency order, each with
 *  the list's plain-English definition, null for the {len(missing)} words it leaves undefined. */
export const TOEIC_LIST: readonly (readonly [word: string, definition: string | null])[] = [
{lines},
]
''')
print(len(words), 'words,', len(missing), 'without a definition:', ' '.join(missing))
